"""Streaming-aware wrapper around Pipecat's ``OpenAITTSService``.

Two extensions over upstream:

1. **Network-error redaction.** Pipecat's upstream ``OpenAITTSService.run_tts``
   only catches ``BadRequestError`` and re-yields it as an ``ErrorFrame``.
   Every other exception class — notably ``httpx`` network errors raised
   when the vendored Qwen3-TTS sidecar is slow / down / partitioned from
   the agent's docker network — propagates out of the async generator and
   tears the whole session down, which a LiveKit client sees as a silent
   disconnect. This module catches the network-class exceptions and
   yields a redacted ``ErrorFrame`` so callers see a normal TTS failure
   rather than a dropped session.

2. **Streaming-body request.** OpenAI's speech endpoint does not natively
   expose a streaming parameter, but the Qwen3-TTS sidecar (see
   ``infra/qwen3-tts-wrapper/api/routers/openai_compatible.py:425``)
   accepts ``stream=True`` in the request body and yields PCM chunks as
   they are generated by the model. Without the flag, the sidecar buffers
   the full utterance and ships it after synth completes — on our L4 with
   the 1.7B-CustomVoice variant the observed TTFB is ~20s. Injecting
   ``stream=True`` via ``extra_body`` drops TTFB to the first chunk's
   generation latency (~1-2s), which is what makes the engine usable for
   conversation. Upstream Pipecat cannot do this because ``openai-sdk``
   does not define ``stream`` on ``audio.speech.create`` — we bypass the
   constraint by using ``extra_body``, which the SDK forwards verbatim.
"""

from __future__ import annotations

from collections.abc import AsyncGenerator

import httpx
from loguru import logger
from openai import BadRequestError
from pipecat.frames.frames import ErrorFrame, Frame, TTSAudioRawFrame
from pipecat.services.openai.tts import OpenAITTSService
from pipecat.utils.tracing.service_decorators import traced_tts


# Network-class httpx exceptions that must not tear down the pipeline.
# Listed explicitly (not ``httpx.HTTPError`` broadly) so that 4xx/5xx
# ``HTTPStatusError`` responses still reach Pipecat's own error handler
# — those signal a server-understood problem (bad voice name, bad
# model alias) that benefit from the upstream ``BadRequestError``
# translation path.
_NETWORK_EXCEPTIONS: tuple[type[BaseException], ...] = (
    httpx.ConnectError,
    httpx.ConnectTimeout,
    httpx.ReadTimeout,
    httpx.WriteTimeout,
    httpx.PoolTimeout,
    httpx.RemoteProtocolError,
    httpx.NetworkError,
)


class Qwen3TTSService(OpenAITTSService):
    """``OpenAITTSService`` that streams body bytes from the Qwen3-TTS sidecar.

    Overrides ``run_tts`` to:

    * pass ``extra_body={"stream": True}`` so the sidecar emits PCM chunks
      as they're generated (slashes TTFB from ~20s to ~1-2s on the L4);
    * catch network-class ``httpx`` exceptions and yield a redacted
      ``ErrorFrame`` instead of propagating (matches the failure mode of
      ``GigaAMSTTService`` / ``SileroTTSService``).

    Every other aspect (voice whitelisting, model routing, TTFB metrics,
    frame shape) inherits from the upstream implementation.
    """

    @traced_tts
    async def run_tts(self, text: str, context_id: str) -> AsyncGenerator[Frame, None]:
        """Stream speech bytes from the Qwen3-TTS sidecar.

        Mirrors Pipecat's upstream ``OpenAITTSService.run_tts`` (pipecat
        0.0.108 at ``pipecat/services/openai/tts.py``) with one behavioural
        change: ``stream=True`` is injected via ``extra_body``. See module
        docstring for rationale.
        """
        logger.debug(f"{self}: Generating TTS [{text}]")
        try:
            # Two legal shapes for ``self._settings.voice``:
            #   1. An OpenAI whitelist name (``alloy``, ``echo``, ...).
            #      Map through ``VALID_VOICES`` — preserves the upstream
            #      translation path so runtime TTSUpdateSettingsFrame
            #      updates still route consistently.
            #   2. A ``clone:<profile>`` identifier pointing at a
            #      voice-library profile baked into the Qwen3-TTS
            #      wrapper image (Base variants). The wrapper intercepts
            #      this prefix before its own voice mapping, so the
            #      OpenAI whitelist does not apply — passing it verbatim
            #      is what the wrapper expects. Without this bypass,
            #      VALID_VOICES[...] raises KeyError at request time and
            #      the pipeline plays silence.
            from pipecat.services.openai.tts import VALID_VOICES  # noqa: PLC0415

            voice_id = self._settings.voice
            request_voice = (
                voice_id
                if isinstance(voice_id, str) and voice_id.startswith("clone:")
                else VALID_VOICES[voice_id]
            )
            create_params = {
                "input": text,
                "model": self._settings.model,
                "voice": request_voice,
                "response_format": "pcm",
            }
            if self._settings.instructions:
                create_params["instructions"] = self._settings.instructions
            if self._settings.speed:
                create_params["speed"] = self._settings.speed

            # The Qwen3-TTS wrapper reads ``stream`` from the request
            # body (api/routers/openai_compatible.py:425). openai-sdk
            # does not define ``stream`` on audio.speech.create, so we
            # inject it via extra_body, which the SDK forwards verbatim.
            async with self._client.audio.speech.with_streaming_response.create(
                extra_body={"stream": True},
                **create_params,
            ) as r:
                if r.status_code != 200:
                    error = await r.text()
                    logger.error(
                        f"{self} error getting audio (status: {r.status_code}, error: {error})"
                    )
                    yield ErrorFrame(
                        error=f"Error getting audio (status: {r.status_code}, error: {error})"
                    )
                    return

                await self.start_tts_usage_metrics(text)

                chunk_size = self.chunk_size

                async for chunk in r.iter_bytes(chunk_size):
                    if len(chunk) > 0:
                        await self.stop_ttfb_metrics()
                        yield TTSAudioRawFrame(
                            chunk,
                            self.sample_rate,
                            1,
                            context_id=context_id,
                        )
        except BadRequestError as e:
            yield ErrorFrame(error=f"Unknown error occurred: {e}")
        except _NETWORK_EXCEPTIONS:
            # Log the full exception server-side (includes the target
            # URL and the httpx error detail); emit a generic string
            # downstream so nothing about the sidecar's deploy shape
            # leaks into the LiveKit data channel.
            logger.exception("Qwen3 sidecar request failed")
            yield ErrorFrame("TTS synth failed")
